// Code generated by protoc-gen-go. DO NOT EDIT.
// source: evaDemo.proto

package evaDemo

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Nil struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nil) Reset()         { *m = Nil{} }
func (m *Nil) String() string { return proto.CompactTextString(m) }
func (*Nil) ProtoMessage()    {}
func (*Nil) Descriptor() ([]byte, []int) {
	return fileDescriptor_81feb6e4154a3353, []int{0}
}

func (m *Nil) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nil.Unmarshal(m, b)
}
func (m *Nil) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nil.Marshal(b, m, deterministic)
}
func (m *Nil) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nil.Merge(m, src)
}
func (m *Nil) XXX_Size() int {
	return xxx_messageInfo_Nil.Size(m)
}
func (m *Nil) XXX_DiscardUnknown() {
	xxx_messageInfo_Nil.DiscardUnknown(m)
}

var xxx_messageInfo_Nil proto.InternalMessageInfo

type HelloReq struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32             `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	C                    *HelloReq_Content `protobuf:"bytes,3,opt,name=c,proto3" json:"c,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *HelloReq) Reset()         { *m = HelloReq{} }
func (m *HelloReq) String() string { return proto.CompactTextString(m) }
func (*HelloReq) ProtoMessage()    {}
func (*HelloReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_81feb6e4154a3353, []int{1}
}

func (m *HelloReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReq.Unmarshal(m, b)
}
func (m *HelloReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReq.Marshal(b, m, deterministic)
}
func (m *HelloReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReq.Merge(m, src)
}
func (m *HelloReq) XXX_Size() int {
	return xxx_messageInfo_HelloReq.Size(m)
}
func (m *HelloReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReq.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReq proto.InternalMessageInfo

func (m *HelloReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HelloReq) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *HelloReq) GetC() *HelloReq_Content {
	if m != nil {
		return m.C
	}
	return nil
}

type HelloReq_Content struct {
	C1                   string   `protobuf:"bytes,1,opt,name=c1,proto3" json:"c1,omitempty"`
	C2                   int32    `protobuf:"varint,2,opt,name=c2,proto3" json:"c2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReq_Content) Reset()         { *m = HelloReq_Content{} }
func (m *HelloReq_Content) String() string { return proto.CompactTextString(m) }
func (*HelloReq_Content) ProtoMessage()    {}
func (*HelloReq_Content) Descriptor() ([]byte, []int) {
	return fileDescriptor_81feb6e4154a3353, []int{1, 0}
}

func (m *HelloReq_Content) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReq_Content.Unmarshal(m, b)
}
func (m *HelloReq_Content) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReq_Content.Marshal(b, m, deterministic)
}
func (m *HelloReq_Content) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReq_Content.Merge(m, src)
}
func (m *HelloReq_Content) XXX_Size() int {
	return xxx_messageInfo_HelloReq_Content.Size(m)
}
func (m *HelloReq_Content) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReq_Content.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReq_Content proto.InternalMessageInfo

func (m *HelloReq_Content) GetC1() string {
	if m != nil {
		return m.C1
	}
	return ""
}

func (m *HelloReq_Content) GetC2() int32 {
	if m != nil {
		return m.C2
	}
	return 0
}

func init() {
	proto.RegisterType((*Nil)(nil), "evaDemo.Nil")
	proto.RegisterType((*HelloReq)(nil), "evaDemo.HelloReq")
	proto.RegisterType((*HelloReq_Content)(nil), "evaDemo.HelloReq.Content")
}

func init() { proto.RegisterFile("evaDemo.proto", fileDescriptor_81feb6e4154a3353) }

var fileDescriptor_81feb6e4154a3353 = []byte{
	// 192 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x2d, 0x4b, 0x74,
	0x49, 0xcd, 0xcd, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x58, 0xb9,
	0x98, 0xfd, 0x32, 0x73, 0x94, 0x5a, 0x18, 0xb9, 0x38, 0x3c, 0x52, 0x73, 0x72, 0xf2, 0x83, 0x52,
	0x0b, 0x85, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83,
	0xc0, 0x6c, 0x21, 0x01, 0x2e, 0xe6, 0xc4, 0xf4, 0x54, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xd6, 0x20,
	0x10, 0x53, 0x48, 0x9d, 0x8b, 0x31, 0x59, 0x82, 0x59, 0x81, 0x51, 0x83, 0xdb, 0x48, 0x52, 0x0f,
	0x66, 0x3a, 0xcc, 0x0c, 0x3d, 0xe7, 0xfc, 0xbc, 0x92, 0xd4, 0xbc, 0x92, 0x20, 0xc6, 0x64, 0x29,
	0x4d, 0x2e, 0x76, 0x28, 0x4f, 0x88, 0x8f, 0x8b, 0x29, 0xd9, 0x10, 0x6a, 0x2e, 0x53, 0xb2, 0x21,
	0x98, 0x6f, 0x04, 0x35, 0x94, 0x29, 0xd9, 0xc8, 0x28, 0x9c, 0x8b, 0xdd, 0x15, 0x62, 0x92, 0x90,
	0x12, 0x17, 0x4b, 0x40, 0x66, 0x5e, 0xba, 0x10, 0x0f, 0xdc, 0x6c, 0xbf, 0xcc, 0x1c, 0x29, 0x14,
	0x9e, 0x90, 0x06, 0x17, 0x2b, 0xd8, 0x42, 0x21, 0x41, 0x0c, 0x07, 0xa0, 0xaa, 0x4c, 0x62, 0x03,
	0x7b, 0xdb, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x16, 0x69, 0xad, 0x5b, 0x07, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EvaDemoClient is the client API for EvaDemo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EvaDemoClient interface {
	Ping(ctx context.Context, in *Nil, opts ...grpc.CallOption) (*Nil, error)
	Hello(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*Nil, error)
}

type evaDemoClient struct {
	cc *grpc.ClientConn
}

func NewEvaDemoClient(cc *grpc.ClientConn) EvaDemoClient {
	return &evaDemoClient{cc}
}

func (c *evaDemoClient) Ping(ctx context.Context, in *Nil, opts ...grpc.CallOption) (*Nil, error) {
	out := new(Nil)
	err := c.cc.Invoke(ctx, "/evaDemo.EvaDemo/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *evaDemoClient) Hello(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*Nil, error) {
	out := new(Nil)
	err := c.cc.Invoke(ctx, "/evaDemo.EvaDemo/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EvaDemoServer is the server API for EvaDemo service.
type EvaDemoServer interface {
	Ping(context.Context, *Nil) (*Nil, error)
	Hello(context.Context, *HelloReq) (*Nil, error)
}

// UnimplementedEvaDemoServer can be embedded to have forward compatible implementations.
type UnimplementedEvaDemoServer struct {
}

func (*UnimplementedEvaDemoServer) Ping(ctx context.Context, req *Nil) (*Nil, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedEvaDemoServer) Hello(ctx context.Context, req *HelloReq) (*Nil, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}

func RegisterEvaDemoServer(s *grpc.Server, srv EvaDemoServer) {
	s.RegisterService(&_EvaDemo_serviceDesc, srv)
}

func _EvaDemo_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Nil)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EvaDemoServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/evaDemo.EvaDemo/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EvaDemoServer).Ping(ctx, req.(*Nil))
	}
	return interceptor(ctx, in, info, handler)
}

func _EvaDemo_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EvaDemoServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/evaDemo.EvaDemo/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EvaDemoServer).Hello(ctx, req.(*HelloReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _EvaDemo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "evaDemo.EvaDemo",
	HandlerType: (*EvaDemoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _EvaDemo_Ping_Handler,
		},
		{
			MethodName: "Hello",
			Handler:    _EvaDemo_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "evaDemo.proto",
}
